version: "3.9"

services:
  telegram-bot:
    container_name: telegram_bot_ege
    working_dir: /telegram_bot_ege
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
    command: sh -c "python main.py"

  db:
    container_name: telegram_bot_ege_bd
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: scot
      POSTGRES_PASSWORD: tiger
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
