version: "3.9"

services:
  telegram-bot:
    container_name: telegram_bot_ege
    working_dir: /telegram_bot_ege
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
    command: sh -c "python main.py"
