"""new_column_score

Revision ID: 25a40e4769ea
Revises: 53b5067c5d53
Create Date: 2024-10-29 16:58:00.877424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25a40e4769ea'
down_revision: Union[str, None] = '53b5067c5d53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('score', sa.SmallInteger(), nullable=False, comment='Баллы'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'score')
    # ### end Alembic commands ###
