"""added_user_table

Revision ID: 53b5067c5d53
Revises: 
Create Date: 2024-10-29 14:27:59.107996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b5067c5d53'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор'),
    sa.Column('name', sa.String(length=1000), nullable=False, comment='Имя'),
    sa.Column('surname', sa.String(length=200), nullable=False, comment='Фамилия'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
