"""init_revision

Revision ID: 6c3b03804b4d
Revises: 
Create Date: 2024-10-30 14:32:40.602964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c3b03804b4d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Имя'),
    sa.Column('surname', sa.String(length=200), nullable=False, comment='Фамилия'),
    sa.Column('telegram_user_id', sa.Integer(), nullable=False, comment='Уникальный идентификатор пользователя в телеграмм'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_user_id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор'),
    sa.Column('name', sa.Enum('RUSSIAN_LANGUAGE', 'LITERATURE', 'FOREIGN_LANGUAGE', 'ALGEBRA', 'GEOMETRY', 'PHYSICS', 'CHEMISTRY', 'BIOLOGY', 'GEOGRAPHY', 'INFORMATICS', 'HISTORY', 'LOCAL_STUDIES', 'WORLD_ART_CULTURE', 'SOCIAL_STUDIES', 'SAFETY_OF_LIFE', 'FINANCIAL_LITERACY', 'ECONOMICS', 'PHYSICAL_EDUCATION', 'PROJECT_ACTIVITY', name='subjectenum'), nullable=False, comment='Название школьного предмета'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор'),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False, comment='Баллы'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_table('subjects')
    op.drop_table('students')
    # ### end Alembic commands ###
