"""init_revision

Revision ID: ee159a891276
Revises:
Create Date: 2024-10-30 17:30:49.477551

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'ee159a891276'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'students',
        sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор'),
        sa.Column('name', sa.String(length=200), nullable=False, comment='Имя'),
        sa.Column('surname', sa.String(length=200), nullable=False, comment='Фамилия'),
        sa.Column(
            'telegram_user_id',
            sa.Integer(),
            nullable=False,
            comment='Уникальный идентификатор пользователя в телеграмм',
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('telegram_user_id'),
    )

    op.create_table(
        'subjects',
        sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор'),
        sa.Column('name', sa.String(), nullable=False, comment='Название школьного предмета'),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_table(
        'scores',
        sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор'),
        sa.Column('student_id', sa.Integer(), nullable=False),
        sa.Column('subject_id', sa.Integer(), nullable=False),
        sa.Column('score', sa.SmallInteger(), nullable=False, comment='Баллы'),
        sa.ForeignKeyConstraint(
            ['student_id'],
            ['students.id'],
        ),
        sa.ForeignKeyConstraint(
            ['subject_id'],
            ['subjects.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###

    # Определяем объект таблицы subjects
    subjects_table = sa.Table('subjects', sa.MetaData(), autoload_with=op.get_bind())  # Загружаем метаданные таблицы

    # Вставляем данные в таблицу subjects
    subjects = [
        {'name': 'Русский язык'},
        {'name': 'Литература'},
        {'name': 'Иностранный язык'},
        {'name': 'Алгебра'},
        {'name': 'Геометрия'},
        {'name': 'Физика'},
        {'name': 'Химия'},
        {'name': 'Биология'},
        {'name': 'География'},
        {'name': 'Информатика (ИКТ)'},
        {'name': 'История'},
        {'name': 'Краеведение'},
        {'name': 'Мировая художественная культура (МХК)'},
        {'name': 'Обществознание'},
        {'name': 'Основы безопасности жизнедеятельности'},
        {'name': 'Основы финансовой грамотности'},
        {'name': 'Основы экономики (экономика)'},
        {'name': 'Физическая культура'},
        {'name': 'Проектная деятельность'},
    ]

    # Вставляем данные в таблицу subjects
    op.bulk_insert(subjects_table, subjects)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_table('subjects')
    op.drop_table('students')
    # ### end Alembic commands ###
